import rules from './rules'

export default {
  loginTitle: 'Login',
  loginButton: 'Log in',
  emailPlaceHolder: 'email',
  passwordPlaceHolder: 'password',
  emailError: 'Invalid email',
  passwordError: `Password min length is ${rules.passwordMinLengh}`,
  logoutButton: 'Log out',
  calendarTitle: 'Календар',
  customersTitle: 'Клієнти',
  customerInfo: 'Клієнт(-ка)',
  weekDaysShort: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'],
  months: [
    'Січень',
    'Лютий',
    'Березень',
    'Квітень',
    'Травень',
    'Червень',
    'Липень',
    'Серпень',
    'Вересень',
    'Жовтень',
    'Листопад',
    'Грудень',
  ],
  working: 'Працює',
  dayOff: 'Вихідний',
  createProcedure: 'Створити запис',
  searchClient: 'пошук клієнта(-ки)',
  name: "ім'я",
  phone: 'телефон',
  messenger: 'месенджер',
  link: 'посилання',
}
